// Package store reads and writes the catalog as a tree of files, one per
// model.
//
// The data in this repository is generated by scraping, so it is rewritten in
// full on every run. One file per model is what keeps that reviewable: a
// vendor raising one rate shows up as a three-line diff in one file rather
// than as a change buried in a hundred-thousand-line document, two runs
// touching different providers do not conflict, and the git history becomes an
// audit trail of every price change a vendor has ever made.
//
// The aggregate is written for consumers who want a single fetch. It is built
// by reading the tree back off disk rather than from the run that produced it,
// so syncing one provider never drops the others from it.
package store
